apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: A description of my service
  tags:
    - api
    - backend
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/api-spec: url:https://raw.githubusercontent.com/DmytroSaliuk/dx-marketplace-check/main/openapi.json
spec:
  type: service
  lifecycle: production
  owner: user:guest





