apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: A description of my service
  tags:
    - api
    - backend
spec:
  type: service
  lifecycle: production
  owner: user:guest
  providesApis:
    - api: my-service-api
      spec:
        url: https://raw.githubusercontent.com/DmytroSaliuk/dx-marketplace-check/main/openapi.json



